theme = "nord"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[keys.normal.space]
c = ":sh kitty @ send-text --match 'num:1' cargo run -- Cargo.toml \\\\n"

[keys.insert]
C-a = [ "goto_line_start" ]
C-e = [ "goto_line_end" ]

[keys.normal]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
x = "delete_selection"
0 = "goto_line_start"
"$" = "goto_line_end"

V = ["select_mode", "extend_to_line_bounds"]

p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]

C-a = [ "goto_line_start" ]
C-e = [ "goto_line_end" ]
C-j = [ "move_visual_line_down", "goto_next_paragraph", "trim_selections" ]
C-k = [ "move_visual_line_up", "goto_prev_paragraph", "trim_selections" ]

[keys.normal.d]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]

[keys.normal.y]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]
